# Enable mouse emulation.
# CONFIG_ZMK_POINTING=y

# Change idle settings
CONFIG_ZMK_IDLE_TIMEOUT=30000

# Deep sleep settings
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=3600000

# Custom keyboard name (max. 16 characters)
CONFIG_ZMK_KEYBOARD_NAME="HB Corne BT"

CONFIG_BT_BAS=y
CONFIG_ZMK_BATTERY_REPORTING=y
# Split keyboard only: enable peripheral battery fetching
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_STATUS_ADV_CENTRAL_SIDE="LEFT"

CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_ZMK_RGB_UNDERGLOW_ON_START=n
CONFIG_ZMK_RGB_UNDERGLOW_HUE_START=170
CONFIG_ZMK_RGB_UNDERGLOW_SAT_START=100
CONFIG_ZMK_RGB_UNDERGLOW_BRT_START=20

CONFIG_ZMK_DISPLAY=n
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=y
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_USB=y

# Prospector ZMK Module
# Enable status advertisement
CONFIG_ZMK_STATUS_ADVERTISEMENT=y
CONFIG_ZMK_STATUS_ADV_KEYBOARD_NAME="HB Corne BT"